name: linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: deps
      run: |
        sudo apt update
        sudo apt install -yq build-essential gcc-10 g++-10 cmake libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libsdl2-dev libsdl2-ttf-dev libglm-dev
    - name: gcc
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
    - name: make
      run: ./package-linux.sh
    - name: factropy-linux
      uses: actions/upload-artifact@v2
      with:
        name: factropy-linux
        path: factropy-linux.zip
        retention-days: 1


